-- CONSULTAS COM SELECT 
DESC EMPLOYEES;

SELECT * FROM EMPLOYEES;

DESC JOBS;

SELECT * FROM JOBS;

SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, SALARY
FROM EMPLOYEES;

--USANDO ALIAS E PARENTESES PARA PROCEDENCIA
SELECT FIRST_NAME, LAST_NAME, SALARY, (SALARY + 100) * 1.15 AS AUMENTO
FROM EMPLOYEES;

--ELIMINANDO VALORES NULOS 
SELECT FIRST_NAME, LAST_NAME, JOB_ID, SALARY, COMMISSION_PCT,
       2000 * COMMISSION_PCT AS COMISSAO
FROM EMPLOYEES
WHERE COMMISSION_PCT IS NOT NULL;

--CONCATENAÇÃO
SELECT FIRST_NAME ||' '|| LAST_NAME ||', DATA DE ADMISSÃO: '|| HIRE_DATE "FUNCIONARIO"
FROM EMPLOYEES;

SELECT DEPARTMENT_NAME ||' , ID GERENTE: '|| MANAGER_ID "DEPARTAMENTO E GERENTE"
FROM DEPARTMENTS;      

SELECT DEPARTMENT_ID
FROM EMPLOYEES;

--DISTINCT PARA ELIMINAR LINHAS DUPLICADAS
SELECT DISTINCT DEPARTMENT_ID
FROM EMPLOYEES;
--------------------------------------------------------------------------------

--ULTILIZANDO A CLAUSULA WHERE 
SELECT EMPLOYEE_ID, LAST_NAME, JOB_ID, DEPARTMENT_ID
FROM EMPLOYEES
WHERE JOB_ID = 'IT_PROG';

SELECT FIRST_NAME, LAST_NAME, JOB_ID, DEPARTMENT_ID, HIRE_DATE
FROM EMPLOYEES
WHERE LAST_NAME = 'King';

SELECT FIRST_NAME, LAST_NAME, JOB_ID, DEPARTMENT_ID, HIRE_DATE
FROM EMPLOYEES
WHERE HIRE_DATE = '31/01/04';

--MAIOR OU IGUAL
SELECT LAST_NAME, SALARY
FROM EMPLOYEES
WHERE SALARY >= 10000;

--BETWEEN 
SELECT LAST_NAME, SALARY
FROM EMPLOYEES
WHERE SALARY BETWEEN 10000 AND 14000;

--IN 
SELECT EMPLOYEE_ID, LAST_NAME, SALARY, MANAGER_ID, JOB_ID
FROM EMPLOYEES
WHERE JOB_ID IN ('IT_PROG', 'FI_ACCOUNT', 'SA_REP');

--LIKE 
SELECT FIRST_NAME, LAST_NAME, JOB_ID
FROM EMPLOYEES
WHERE FIRST_NAME LIKE 'A%';

SELECT FIRST_NAME, LAST_NAME, JOB_ID
FROM EMPLOYEES
WHERE LAST_NAME LIKE '%a';

--AND
SELECT EMPLOYEE_ID, LAST_NAME, JOB_ID, SALARY 
FROM EMPLOYEES
WHERE SALARY >= 5000
AND JOB_ID = 'IT_PROG';

--OR
SELECT EMPLOYEE_ID, LAST_NAME, JOB_ID, SALARY 
FROM EMPLOYEES
WHERE SALARY >= 5000
OR JOB_ID = 'IT_PROG';

--NOT
SELECT EMPLOYEE_ID, LAST_NAME, JOB_ID, MANAGER_ID, SALARY 
FROM EMPLOYEES
WHERE JOB_ID NOT IN ('IT_PROG', 'SA_REP');

--ORDER BY
SELECT LAST_NAME, JOB_ID, DEPARTMENT_ID, HIRE_DATE
FROM EMPLOYEES
ORDER BY HIRE_DATE ASC;

SELECT LAST_NAME, JOB_ID, DEPARTMENT_ID, HIRE_DATE
FROM EMPLOYEES
ORDER BY HIRE_DATE DESC;

SELECT LAST_NAME SOBRENOME, JOB_ID, DEPARTMENT_ID, HIRE_DATE
FROM EMPLOYEES
ORDER BY SOBRENOME ASC;

SELECT LAST_NAME SOBRENOME, JOB_ID, DEPARTMENT_ID, HIRE_DATE
FROM EMPLOYEES
ORDER BY 2 DESC;

--VARIAVEIS DE SUBSTITUIÇÃO
SELECT EMPLOYEE_ID, DEPARTMENT_ID, SALARY
FROM EMPLOYEES
WHERE EMPLOYEE_ID = &EMPLOYEE_ID;

SELECT EMPLOYEE_ID, DEPARTMENT_ID, SALARY
FROM EMPLOYEES
WHERE EMPLOYEE_ID = &&EMPLOYEE_ID;

SELECT LAST_NAME, DEPARTMENT_ID, JOB_ID, SALARY
FROM EMPLOYEES
WHERE JOB_ID = '&JOB_ID';
--------------------------------------------------------------------------------
--CAIXA ALTA E BAIXA
SELECT employee_id, last_name, department_id
FROM employees
WHERE LOWER(last_name) = 'KING';

SELECT employee_id, last_name, department_id
FROM employees
WHERE UPPER(last_name) = 'KING';

-- Funções de Manipulação de Caracteres

SELECT CONCAT(' Curso: ','Introdução ORACLE 19c'), SUBSTR('Introdução ORACLE 19c',1,11),
       LENGTH('Introdução ORACLE 19c'), INSTR('Introdução ORACLE 19c','ORACLE')
FROM dual;

SELECT job_title, REPLACE(job_title, 'President', 'Presidente') CARGO
FROM jobs
WHERE  job_title = 'President';

-- Funções tipo NUMBER

SELECT ROUND(45.923,2), ROUND(45.923,0) ARREDONDAR
FROM dual;

SELECT TRUNC(45.923,2), TRUNC(45.923,0)
FROM dual;

SELECT MOD(1300,600) RESTO
FROM dual;

SELECT ABS(-9), SQRT(9)
FROM dual;

-- Funções tipo DATE 

SELECT sysdate
FROM dual;

-- Cálculos com Datas

SELECT sysdate, sysdate + 30, sysdate + 60, sysdate - 30
FROM dual;

SELECT last_name, ROUND((SYSDATE-hire_date)/7,2) "SEMANAS DE TRABALHO'"
FROM employees;

-- Outras Funções tipo DATE

SELECT first_name, last_name, ROUND(MONTHS_BETWEEN(sysdate, hire_date),2) "MESES DE TRABALHO"
FROM employees;

SELECT SYSDATE, ADD_MONTHS(SYSDATE, 3), NEXT_DAY(SYSDATE,'SEXTA FEIRA'), LAST_DAY(SYSDATE)
FROM   dual;

SELECT sysdate, ROUND(SYSDATE, 'MONTH'), ROUND(SYSDATE, 'YEAR'), 
       TRUNC(SYSDATE, 'MONTH'), TRUNC(SYSDATE, 'YEAR')
FROM   dual;
       
SELECT SYSDATE, TO_CHAR(TRUNC(SYSDATE),'DD/MM/YYYY HH24:MI:SS')
FROM  dual;




